### PR TITLE
SEL32: Change diagnostic output to fixed fields.

### PR DESCRIPTION
**Pull request by AZBevier**
SEL32: Add changes to instruction processing to pass more SEL32 diagnostics.

### CODE REVIEW

**Comment by rcornwell** [comment]
Before commit, please verify that the simulators compile without any warnings. 

Also the diags hang at:
START CV.TRP.H (#111031-241H 09MAY88)

**Comment by AZBevier** [comment]
Rich,

I do not have any warning on compile.  I use the Makefile you provided.  I am using Fedora 29, so what did you see as warnings?

Jim

**Comment by rcornwell** [comment]
diff --git a/SEL32/sel32_com.c b/SEL32/sel32_com.c
index bbbad70..1959ced 100644
--- a/SEL32/sel32_com.c
+++ b/SEL32/sel32_com.c
@@ -794,7 +794,7 @@ endit:
                 goto endit;                             /* done */
             /* just dump the char */
 //          /* xmt disabled, just wait around */
-            sim_debug(DEBUG_CMD, &com_dev, "com_srvo write dumping char %c on line %04\n", ch, ln);
+            sim_debug(DEBUG_CMD, &com_dev, "com_srvo write dumping char %c on line %04x\n", ch, ln);^M
             tmxr_poll_tx(&com_desc);                    /* poll xmt */
 //??            sim_activate(uptr, coml_unit[ln].wait);     /* wait */
             sim_activate(uptr, uptr->wait);             /* wait */
diff --git a/SEL32/sel32_scfi.c b/SEL32/sel32_scfi.c
index 7ea7e9f..bc6a149 100644
--- a/SEL32/sel32_scfi.c
+++ b/SEL32/sel32_scfi.c
@@ -867,7 +867,7 @@ rddone:
                     if (i == 0) {
                         uptr->u3 &= ~(0xffff);  /* remove old status bits & cmd */
                         sim_debug(DEBUG_DATAIO, dptr,
-                            "DISK Wrote %04x bytes to diskfile cyl %04x hds %02x sec %02x tstart %08\n",
+                            "DISK Wrote %04x bytes to diskfile cyl %04x hds %02x sec %02x tstart %08x\n",^M
                             data->dlen, data->cyl, data->tpos, data->spos, data->tstart);
                         chan_end(chsa, SNS_CHNEND|SNS_DEVEND);
                         goto wrdone;


I am not sure how you missed these missing format specifiers.

**Comment by AZBevier** [comment]
Rich,

I used the makefile in the simh build and it does not provide any warnings for the two lines you provided on my system.  Thanks for catching them.  I added –Wall to the Makefile and those statement were not flagged by the compiler.  Lots of other warning, but not those.  I guess two people looking is better than one and the gnu compiler. 

If you want to run one diag at a time for a specific machine you need to uncomment the deposit bootr[0] ffffffff.  This tells the diags loader to not use the command file.  You will get a DOL> prompt.  Set the cpu type in the diag.ini file too to what you want to test.  At the prompt load the diag you want to run:

DOL>LOAD CV.CP3
DOL>RESET CV.CP3 OPT 10 11
DOL>START CV.CP3 PASS(100)

DOL>LOAD CV.CON
DOL>RESET CV.CON OPT 10 11
DOL>SET CV.CON OPT 8
DOL>START CV.CON PASS(1)

Look at the normal output for the options to specify (or see the diag doc).  I could use some help with the CV.CON diag.  It is doing some timing test that I can not figure out.  It is the console test.

Jim

**Pull request merged**
