### PR TITLE
KA10: SAIL spacewar buttons

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Add SAIL spacewar buttons.   Similar to MIT's spacewar consoles.

Bits are read with CONI TV.  TV is device 404 "TV camera interface".

Button bits are, from SW[SW,REG]:

```
TPBIT:  1                               ;BIT SIGNIFYING TORP LAUNCH
        20
        400
        10000
        200000
THRUBT: 2
        40
        1000
        20000
        400000
ROTRBT: 4
        100
        2000
        40000
        1000000
ROTLBT: 10
        200
        4000
        100000
        2000000
```

FYI @bgbaumgart

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Buttons are emulated using gamepad controllers like the MIT Spacewar consoles.

**Comment by bgbaumgart** [comment]
OK. now let's see if I can close this thread.

**Comment by larsbrinkhoff** [comment]
This should not be closed.  It's a pull request for @rcornwell's repository.

**Comment by larsbrinkhoff** [comment]
Rebased.

**Pull request merged**
