### PR TITLE
SEL32: Add three missing basemode instructions.

### PR DESCRIPTION
**Pull request by AZBevier**
SEL32: Handle multiple EOFs on MT.
SEL32: Correct basemode instruction processing and display errors.
SEL32:Fix ex -m to display basemode instructions.

### CODE REVIEW

**Comment by AZBevier** [comment]
With changes diags CP1, CP2, CP3, EAD run OK.  CV.BRD (basemode instructions) fails at test 37 which is CALL instruction.  Will continue working.  UTX tape will load when memory size is 8MB or larger.  Loads bss, text, data from first file, memdisk from 2nd file.  Starts execution at 0x1200 and goes into endless loop near 107f4 after several seconds.  Setting r7 at boot time to 0x40 gives verbose boot information.  Still do not know disk requirements, but it will most likely will be scsi, so sel32_scfi.c handles scsi disks.  That part of UTX code not run yet.

**Comment by rcornwell** [comment]
If you want to you can create issues for the bugs you find. And assign them to either you or me. I have a project set up for SEL32 problems.

**Comment by AZBevier** [comment]
I will continue working on diags.  Also some doc....  Will see what issues drop out.

**Comment by rcornwell** [comment]
Why did you close this request?

**Comment by AZBevier** [comment]
Rich,

Am I to leave it open until you do your pull?  or ?  I do not know I should or should not.

Jim

**Comment by rcornwell** [comment]
Yes, leave it open, it will close automatically or I will close it when I pull in your changes.

**Comment by AZBevier** [comment]
OK.  I now know what to do..

**Pull request merged**
