### PR TITLE
KA10: Reverse TEN11 checks.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
As per request in #93.

### CODE REVIEW

**Comment by rcornwell** [comment]
Does this change improve performance any or is it not noticeable?

**Comment by larsbrinkhoff** [comment]
I haven't checked.  Just swapping the checks I'd guess doesn't matter much, especially if you're talking to something across the network.

**Comment by rcornwell** [comment]
It does not matter for the case where you are talking over the network, however 99% of your memory accesses will not be over the network, but to local memory. This saves a mask and conditional branch for each memory access. This way you only check if this really is a PDP11/PDP6 access after you decide you need to do it.

**Comment by larsbrinkhoff** [comment]
Makes sense, I'm all for it!

**Comment by rcornwell** [comment]
I manually added this patch in so I am closing this push request.

**Pull request closed without merging**
