### PR TITLE
SEL32: Allow channel address reconfiguration.

### PR DESCRIPTION
**Pull request by AZBevier**
SEL32: Add disk definitions for UTX and MPX.
SEL32: Add disk initialization for UTX and MPX HSDP & DISK controllers.
SEL32: Add read/write track/sector label simulation for UTX & MPX.
SEL32: Create revised initialization test files for SIMH.

### CODE REVIEW

**Comment by rcornwell** [comment]
I am getting an error undefined dpa_dev.

**Comment by AZBevier** [comment]
Rich,

I build fine with my makefile, but not yours.  The dpa_dev is defined in sel32_defs.h within an #ifdef FOR_UTX that has a #define FOR_UTX in the previous line.  It is referenced in sel32_sys.c and sel32_hsdp.c.  You needs to add sel32_hsdp.c to your makefile and it will build.

Jim

**Comment by rcornwell** [comment]
Hi Jim,

   In the future please add a note to the commit so I can update the
   makefile.

Rich 

> I build fine with my makefile, but not yours.  The dpa_dev is defined
> in sel32_defs.h within an #ifdef FOR_UTX that has a #define FOR_UTX
> in the previous line.  It is referenced in sel32_sys.c and
> sel32_hsdp.c.  You needs to add sel32_hsdp.c to your makefile and it
> will build.
> 
> Jim
> 
> From: Richard Cornwell 
> Sent: Tuesday, February 04, 2020 7:35 PM
> To: rcornwell/sims 
> Cc: James C. Bevier ; Author 
> Subject: Re: [rcornwell/sims] SEL32: Allow channel address
> reconfiguration. (#180)
> 
> I am getting an error undefined dpa_dev.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 



-- 
==========================================================================
Richard Cornwell
rich@sky-visions.com
http://sky-visions.com
LinkedIn:   https://www.linkedin.com/in/richard-cornwell-991076107
==========================================================================

**Comment by AZBevier** [comment]
Rich,

That program has been there for some time.  I guess you just missed it with your last makefile updates.  No big thing.  I really need another view of how to handle the track/sector labels and the data/sector information that the prep program looks at.  It is really a bitch to figure out.  I am going to spend some time looking at the diag errors so we have a clean build test.  Then back to the UTX installs.

Jim

**Pull request merged**
