### PR TITLE
SEL32: Add SEL32 simulator code.

### PR DESCRIPTION
**Pull request by AZBevier**
Initial copy of SEL32 code from Mark's sel-merge repo

### CODE REVIEW

**Comment by rcornwell** [comment]
Please wait until I get the history moved over.

**Comment by AZBevier** [comment]
Rich,

We are having out of state company in about hour, until tomorrow afternoon.  So take your time.  I will be doing other things.

Jim

**Comment by rcornwell** [comment]
This pull will probably not be needed when I get done.

**Comment by rcornwell** [comment]
This code has been merged via history copy from master repository.

**Pull request closed without merging**
