### PR TITLE
KA10: Fix inconsistent address types

### PR DESCRIPTION
**Pull request by markpizz**
auxcpu_base was previously defined as a t_value, while it should have
been a t_addr everywhere.  This then showed where it was referenced
need declaration adjustments to also work with t_addr in expressions.

### CODE REVIEW

**Comment by rcornwell** [comment]
Be careful changing the type of addr in Mem_read_its/Mem_write_its, this is used as an index and passed to page_lookup_its.

**Comment by markpizz** [comment]
No doubt.

However, it is an address, and in this simulator a t_addr is a uint32 which is certainly reasonable for this system, right?  The logic in those procedures compares the supplied values to various other t_addr values such as CPU.capac.

**Comment by rcornwell** [comment]
Mem_read/Mem_write function on the KA are pointers that are set in the initialization routine.

**Comment by larsbrinkhoff** [comment]
The auxcpu base address is a physical address which can be 20 bits.  Even on a KI/KL the maximum is 22 bits, right?  So a 32-bit t_addr should be OK.

Extended addressing could potentially use 30-bit addresses (just 23 on KL10 model B), or 36 if you count byte pointers.

**Comment by markpizz** [comment]
@rcornwell I see what you're talking about.  The Mem_read and Mem_write routines are different for the PDP6 vs the other systems.  A similar change is needed for the PDP6 implementations.

The initial problem was noticed by a link time warning issued on the AppVeyor Release build of the code on Windows.  The PDP10-KA is built near the end of the things.

**Comment by rcornwell** [comment]
The changes also need to be made to all the page_lookup functions. Also don't forget the KL10 branch which I plan to update tonight.

**Comment by larsbrinkhoff** [comment]
Did this show up in Visual Studio?

**Comment by markpizz** [comment]
> The changes also need to be made to all the page_lookup functions. Also don't forget the KL10 branch which I plan to update tonight.

Well, that seems to be a much more pervasive change.  The changes I've made already were simple and bounded to a couple of places.  You are currently using explicit uint32 declarations for AB and PC where the normal simh convention for things like this would be to use a t_addr type.  Look at:

t_stat fprint_sym (FILE *of, t_addr addr, t_value *val, UNIT *uptr, int32 sw);
t_stat parse_sym (CONST char *cptr, t_addr addr, UNIT *uptr, t_value *val, int32 sw);

I think it's best for you to review these things, right?

> Did this show up in Visual Studio?

Yes.

My normal build is for a Debug build which didn't show this.  The last time I did a Release build I didn't review every line in the build log?

**Comment by markpizz** [comment]
It is unless USE_INT64 && USE_ADDR_64 are both true.  Then t_addr is a uint64

**Comment by rcornwell** [comment]
Ok, I can try and go through and switch addresses to t_addr.

**Comment by rcornwell** [comment]
I have changed this in the KL10 branch.

**Comment by rcornwell** [comment]
These changes were done in the KL10 branch, since this is merged this request can be closed.

**Pull request closed without merging**
